import localFont from "next/font/local";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Header from "./_components/header";
import NextAuthProvrder from "./providers/NextAuthProvrder";

export const metadata = {
	title: "Store App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<NextAuthProvrder>
					{/* header */}
					<Header />
					<div className="p-6">{children}</div>

					<ToastContainer />
				</NextAuthProvrder>
			</body>
		</html>
	);
}
